"""initial schema: agents, files, conversations, tasks, conversation_items

Revision ID: 43fb65b29464
Revises:
Create Date: 2026-03-23 09:23:27.256077
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43fb65b29464"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("ix_agents_created_at", "agents", ["created_at"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False, server_default="default"),
        sa.CheckConstraint("kind IN ('default', 'sub_agent')", name="ck_conversations_kind"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_conversations_created_at", "conversations", ["created_at"], unique=False)
    op.create_index("ix_conversations_kind", "conversations", ["kind"], unique=False)
    op.create_table(
        "files",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("bytes", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_files_created_at", "files", ["created_at"], unique=False)
    op.create_table(
        "conversation_items",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("response_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("data", sa.Text(), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_conversation_items_conversation_id_position",
        "conversation_items",
        ["conversation_id", "position"],
        unique=True,
    )
    op.create_index(
        "ix_conversation_items_response_id", "conversation_items", ["response_id"], unique=False
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("conversation_id", sa.String(length=64), nullable=False),
        sa.Column("previous_response_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("inbox_closed", sa.Boolean(), nullable=False),
        sa.Column("agent_name", sa.String(length=256), nullable=False),
        sa.Column("background", sa.Boolean(), nullable=False),
        sa.Column("root_task_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agents.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["root_task_id"],
            ["tasks.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_tasks_agent_id", "tasks", ["agent_id"], unique=False)
    op.create_index("ix_tasks_conversation_id", "tasks", ["conversation_id"], unique=False)
    op.create_index("ix_tasks_created_at", "tasks", ["created_at"], unique=False)
    op.create_index("ix_tasks_root_task_id", "tasks", ["root_task_id"], unique=False)
    op.create_table(
        "pending_tool_calls",
        sa.Column("call_id", sa.String(length=64), nullable=False),
        sa.Column("root_task_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("tool_name", sa.String(length=256), nullable=False),
        sa.Column("arguments", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("result", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "status IN ('action_required', 'completed')",
            name="ck_pending_tool_calls_status",
        ),
        sa.ForeignKeyConstraint(
            ["root_task_id"],
            ["tasks.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("call_id"),
    )
    op.create_index(
        "ix_pending_tool_calls_root_task_id", "pending_tool_calls", ["root_task_id"], unique=False
    )
    op.create_index(
        "ix_pending_tool_calls_task_id", "pending_tool_calls", ["task_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pending_tool_calls_task_id", table_name="pending_tool_calls")
    op.drop_index("ix_pending_tool_calls_root_task_id", table_name="pending_tool_calls")
    op.drop_table("pending_tool_calls")
    op.drop_index("ix_tasks_root_task_id", table_name="tasks")
    op.drop_index("ix_tasks_created_at", table_name="tasks")
    op.drop_index("ix_tasks_conversation_id", table_name="tasks")
    op.drop_index("ix_tasks_agent_id", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index("ix_conversation_items_response_id", table_name="conversation_items")
    op.drop_index(
        "ix_conversation_items_conversation_id_position", table_name="conversation_items"
    )
    op.drop_table("conversation_items")
    op.drop_index("ix_files_created_at", table_name="files")
    op.drop_table("files")
    op.drop_index("ix_conversations_kind", table_name="conversations")
    op.drop_index("ix_conversations_created_at", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("ix_agents_created_at", table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
